### ISSUE TITLE
ImportError: cannot import name 'PdfFileWriter'

### ISSUE THREAD

**Issue by FrancoisSchnell** [mathandy/pdf-split#1]
Hello,

I'm on Python 3.7 32b on windows 10
pip install works well 
" Running setup.py install for pyPdf ... done
Successfully installed pyPdf-1.13"

But when I run the script,

 python pdfsplit.py ateliers.pdf atelier-obs.pdf 3
Traceback (most recent call last):
  File "pdfsplit.py", line 38, in <module>
    from pyPdf import PdfFileWriter, PdfFileReader
  File "C:\Users\franz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyPdf\__init__.py", line 1, in <module>
    from pdf import PdfFileReader, PdfFileWriter
  File "C:\Users\franz\Desktop\PDFmanip\pdf.py", line 1, in <module>
    from pdfsplit import splitPages
  File "C:\Users\franz\Desktop\PDFmanip\pdfsplit.py", line 38, in <module>
    from pyPdf import PdfFileWriter, PdfFileReader
ImportError: cannot import name 'PdfFileWriter' from 'pyPdf' (C:\Users\franz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyPdf\__init__.py)

Any idea? Thanks!

**Comment by ThomIves** [comment]
I am having the same issue but on a Linux Mint 19.1 virtual machine in the Anaconda environment.

**Comment by SHATSON** [comment]
use  PyPDF4
